### ISSUE TITLE
ロゴとファビコンの作成

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blockee#2]
どなたかロゴとファビコンの作成お願いします！（全員で候補だしてみるのもOKです）

- [x] ロゴの作成
- [x] ファビコンの作成

この前自分はこちらのサイトで作成しました
https://www.designevo.com/

できたらいくつか候補を出して欲しいです。それを多数決で決めましょう！

ファビコンは作成したロゴをそのままファビコンジェネレーターを使用して作成できます！
https://favicon.io/favicon-converter/
https://ao-system.net/favicongenerator/

前回作ったときの例：
ロゴ
![logo](https://user-images.githubusercontent.com/66197642/148736969-276de472-0fed-4058-b244-b24ce9050902.jpg)

ファビコン
![sshot 26](https://user-images.githubusercontent.com/72016706/149053167-02f90f67-39ba-485a-afa4-d14cca906a31.png)

**Comment by hirotada-t** [comment]
候補として、ひとつ作ってみました！

・ファビコン
![favicon](https://user-images.githubusercontent.com/68522105/168451149-63d873e0-3384-4179-8cb0-eb2049389c38.png)

・ロゴ
（横）![logo横長](https://user-images.githubusercontent.com/68522105/168451158-e10ce2ff-72e5-4ae2-a7bf-2c112287082a.png)
（角）![logo](https://user-images.githubusercontent.com/68522105/168451168-ed4d6483-4421-4860-b1d3-203c5775a2aa.png)

**Comment by hayato0309** [comment]
二つ作ってみました！

1.
・ロゴ
![logo](https://user-images.githubusercontent.com/45285649/168451546-21218e55-cffa-4770-a801-66d02be47791.png)
・ファビコン
![android-chrome-192x192](https://user-images.githubusercontent.com/45285649/168451551-42154191-43cd-4ec2-b8c7-16c08e450ef5.png)

2.
・ロゴ
![logo](https://user-images.githubusercontent.com/45285649/168451605-f541ae1f-f01a-4f11-90aa-0048ab32eb7f.png)
・ファビコン
![android-chrome-512x512](https://user-images.githubusercontent.com/45285649/168451613-0b512c95-51ef-4e98-94ad-41514d313fd0.png)

**Comment by tkwonn** [comment]
どれもすごく良いです！
@hirotada-t @hayato0309 @hiroto0222 みなさんどれが好みですか？

**Comment by hirotada-t** [comment]
パターン２の、テキストとアイコンを混ぜているのがとてもすこですねー😆

※通し番号【パターン◯◯】を追記してます。

**Comment by hayato0309** [comment]
@hirotada-t 
通し番号ありがとうございます！

僕も自分が作ったものの中だと、パターン2の方が好きですね笑
（もしこれになるようでしたら、配色とか全然調整できます！）

hirotadaさんのやつも、ゲーム内容と連想しやすくていいなと思います！

**Comment by tkwonn** [comment]
@hiroto0222 さんはどうですか？

**Comment by hiroto0222** [comment]
どれもすごくかっこいいアイコン作成頂いて有難うございます! 個人的にはパターン2が最もシンプルでいいと思います!

**Comment by tkwonn** [comment]
それでは多数決としてパターン２を採用します！
