### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blockee#3]
ワイヤーフレームに関する議論はここで行います。
後で調整は可能なので、ある程度の見た目を作成していきましょう。

以下のリンクから編集できるようになっているので、みなさんで作成していきましょう。
https://whimsical.com/ui-prototype-7MGtSvYuvMYymtLz5wLnaE

それからロゴやページをWeek1（20日）のミーティング前までに作成していきましょう。

**Comment by tkwonn** [comment]
こちら編集できなかったりしますか？ w

**Comment by hayato0309** [comment]
ゼロベースでの議論は難しいかもしれないので、一回僕がたたき台作りますね！（遅くとも水曜中には仕上げます）
（デザインセンスのなさはあらかじめご了承をw🙇‍♂️）

**Comment by tkwonn** [comment]
お一人１ページ担当でもいいと思いますよ！
あとこの段階ではデザインには凝らなくて大丈夫かもです。ゲーム自体を完成させてからデザインを仕上げていけるので（アルゴリズムにかける時間がほとんどになるかと思います）
Game Pageはある程度ちゃんと考えたほうがいいかもですね。

みなさんがQuasarフレームワークを使用することに同意でしたら、リポジトリのファイル等を新しいのに変えて実際にページを作成する部分に移りたいと思っています。
目標は20日の土曜日までにある程度の見た目を作成することです！

**Comment by hayato0309** [comment]
@tkwonn 
先ほど帰宅して色々片付いたのでこれから取り掛かるところです😅
今日の夜と明日の朝（仕事に行く前）で片付けようと思っていました！

ある程度ページの構成は考えていたので、他の方への割り振りは大丈夫ですよ！
みなさんにはたくさん意見を出していただければと思っています🙇‍♂️

**Comment by tkwonn** [comment]
@hayato0309 ありがとうございます！ではホームページ(ロゴの配置とか、ログイン画面)をお願いしたいです！

**Comment by tkwonn** [comment]
@hirotada-t さんにはゲームページをお願いしたいです！
@hiroto0222 さんは設定画面を宜しくお願いします！

※デザインは凝らなくて大丈夫です。

**Comment by tkwonn** [comment]
@hayato0309 ありがとうございます！素晴らしい出来ですね。Firebaseで簡単なログイン機能を作ることができるので、HomePageはロゴの横にログインフォームを作ろうかと思います。

設定画面ではTableを使用せずにただ羅列させるだけで大丈夫かと、必要なのは２人対戦か４人対戦かの選択肢とタイムくらいでしょうか。ポジションも最初は角からで決めてしまって大丈夫です

**Comment by hiroto0222** [comment]
@hayato0309 とても丁寧に作成頂きありがとうございます！
- ゲームをスタートするには Firebase でログインしている必要がある場合、現在 HomePage にある Game Start ボダンを Google ログインボタン（Google 認証を使用する場合）で "Get Started" などと表示し、Firebase が提供する popup 認証でログインを行うと良いかと思います！
- Firebase でユーザーのデータを保存する場合、ProfilePage などでユーザーのゲーム履歴、勝率などを表示するのはどうでしょうか？

**Comment by tkwonn** [comment]
@hiroto0222 @hayato0309  @hirotada-t 

@hayato0309 さんがとても丁寧に作成してくださったものに、少し修正を加えてみたので、そちら最終確認お願いします！

**Comment by hayato0309** [comment]
皆さんご確認いただきありがとうございます！

@tkwonn 
確認いたしました！
修正ありがとうございます🙇‍♂️
これでワイヤーフレームはOKだと思います！

**Comment by hirotada-t** [comment]
ありがとうございます！

確認しました。
各プレイヤーの情報が各エリア内にまとまっているので、とてもわかりやすいと思います。

**Comment by tkwonn** [comment]
クローズします！
